<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='ContentStyleSheet.xsl'?>
<!DOCTYPE contentType [
        <!ELEMENT contentType (contents)*>
        <!ELEMENT contents (quote|text|title|photo)*>
        <!ELEMENT text (#PCDATA)>
        <!ELEMENT quote (#PCDATA)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT photo (#PCDATA)>
        ]>

<contentType>

    <contents>
        <title>Joe Biden</title>
        <text>
            Joseph Robinette Biden Jr. (/ˈbaɪdən/ BY-dən; born November 20, 1942) is an American politician and the president-elect of the United States. Having defeated incumbent Donald Trump in the 2020 United States presidential election, he will be inaugurated as the 46th president on January 20, 2021. A member of the Democratic Party, Biden served as the 47th vice president from 2009 to 2017 and a United States senator for Delaware from 1973 to 2009.
            Raised in Scranton, Pennsylvania, and New Castle County, Delaware, Biden studied at the University of Delaware before earning his law degree from Syracuse University in 1968. He was elected a New Castle County Councillor in 1970, and became the sixth-youngest senator in American history when he was elected to the U.S. Senate from Delaware in 1972, at the age of 29. Biden was a longtime member of the Senate Foreign Relations Committee, and eventually its chairman. He opposed the Gulf War in 1991, but supported expanding the NATO alliance into Eastern Europe and its intervention in the Yugoslav Wars of the 1990s. He supported the resolution authorizing the Iraq War in 2002, but opposed the surge of U.S. troops in 2007. He also chaired the Senate Judiciary Committee from 1987 to 1995, dealing with drug policy, crime prevention, and civil liberties issues; led the effort to pass the Violent Crime Control and Law Enforcement Act and the Violence Against Women Act; and oversaw six U.S. Supreme Court confirmation hearings, including the contentious hearings for Robert Bork and Clarence Thomas. He ran unsuccessfully for the Democratic presidential nomination in 1988 and again in 2008.
        </text>

        <quote>
            "I am humbled by the trust and confidence you have placed in me.

                    I pledge to be a president who seeks not to divide, but to unify.

                    Who doesn’t see red and blue states, but a United States."
                    -Joe Biden, Nov 9, 2020
        </quote>
        <photo>
            joe-biden.jpg
        </photo>


    </contents>

</contentType>
